Repository palantir/k8s-spark-scheduler, pull requests merged in 2023-03, with the labels that each got.

#230 When scheduling dynamic executors, order nodes by usage instead of picking a node at random
  internal/extender/resource.go
  internal/extender/resource_test.go
Labels: autorelease, merge when ready

#231 Make node sorting deterministic as it otherwise causes flakes
  internal/sort/nodesorting.go
  internal/sort/nodesorting_test.go
Labels: autorelease

#214 Schedule dynamically allocated executors in same AZ as the initial application
  cmd/server.go
  config/config.go
  internal/common/utils/sets.go
  internal/extender/demand.go
  internal/extender/extendertest/extender_test_utils.go
  internal/extender/resource.go
  internal/extender/resource_test.go
  internal/extender/unschedulablepods_test.go
Labels: autorelease, merge when ready

#238 Explictly encode which BinPacker are single AZ
  internal/extender/binpack.go
  internal/extender/demand.go
  internal/extender/resource.go
Labels: merge when ready

#239 Point single-az-minimal-fragmentation to the correct function
  internal/extender/binpack.go
Labels: autorelease, merge when ready

#244 Include instance group in the metrics
  internal/extender/resource.go
  internal/metrics/binpack.go
  internal/metrics/metrics.go
Labels: autorelease, merge when ready

#247 Bump spark-scheduler-lib to 0.15.0
  go.mod
  go.sum
  vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/binpack/minimal_fragmentation.go
  vendor/github.com/palantir/k8s-spark-scheduler-lib/pkg/capacity/capacity.go
  vendor/modules.txt
Labels: autorelease, merge when ready

#236 Minimize fragmentation for dynamically allocated executors
  internal/extender/binpack.go
  internal/extender/extendertest/extender_test_utils.go
  internal/extender/resource.go
  internal/extender/resource_test.go
  internal/extender/resourcereservations.go
  internal/extender/unschedulablepods_test.go
Labels: autorelease, merge when ready

#248 Add driver/executor collocation metric
  internal/extender/resource.go
  internal/metrics/metrics.go
Labels: autorelease, merge when ready

#249 Report # executors / # nodes used to schedule this application
  internal/extender/resource.go
  internal/metrics/metrics.go
Labels: autorelease, merge when ready
